config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'chatroom#index'
  get '/login', to: 'sessions#new'
  get '/signup', to: 'users#new'
  resources :users
  post '', to: 'messages#create'
  resources :messages
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :messages
  before_save { self.email = email.downcase }
  validates :username, presence: true, length: { minimum: 3, maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user
  def current_user
    @current ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = 'You must be logged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  before_action :require_user
  def index
    @messages = Message.all
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_user
  def new; end

  def create
    @message = Message.new(msg_params)
    @message.user = current_user
    if @message.save
      ActionCable.server.broadcast 'chatroom_channel',
                                   msg: message_render(@message)
    else
      flash[:error] = @message.errors.full_messages
      redirect_to root_path
    end
  end

  def index
    @messages = current_user.messages
  end

  private

  def msg_params
    params.require(:message).permit(:body)
  end

  def message_render(msg)
    render(partial: 'message', locals: { message: msg })
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: %i[new create]
  def new; end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = 'Log in was a succes'
      redirect_to root_path

    else
      flash.now[:error] = 'There was something wrong with your information'
      render 'new'

    end
  end

  def destroy
    session[:user_id] = nil if logged_in?
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:error] = 'You are already logged in'
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to the Message Me #{@user.username}."
      redirect_to root_path
    else
      flash[:error] = @user.errors.full_messages
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned big icon header">
  <i class="orange baseball ball icon"></i>
  Say something
</h2>
<div class="ui two column grid">
<div class="twelve wide column">
<div class="ui fluid raised card chatbox">

  <div class="content" id='messages' >
    <div class="ui feed" id='message-container'>
      <%= render @messages %>

    </div>
  </div>

  <div class="extra content">
      <%= form_with scope: :message,  url: root_path do |f| %>
    <div class="field">
          <div class="ui fluid icon input">
            <%= f.text_field :body %>

      <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
    </div>
    </div>
      <% end %>
  </div>
</div>
</div>



<div class="four wide column">
<div class="ui fluid raised card chatbox">
<div class="content">
<div class="ui inverted vertical menu">
  <a class="active item">
    Home
  </a>
  <a class="item">
    Messages
  </a>
  <a class="item">
    Friends
  </a>
  </div>
  </div>
</div>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="ui inverted mini menu">
<div class="ui container">
  <%= link_to 'Chatroom', root_path, class: 'item'%>
  <%= link_to 'Messages', messages_path, class: 'item'%>

  <div class="right menu">
    <div class="ui dropdown item">
      Account <i class="dropdown icon"></i>
      <div class="menu">        
      <% if logged_in? %>
        <%= link_to 'Log out', logout_path, class: 'item', method: :delete%>
      <% else %>
        <%= link_to 'Log in', login_path, class: 'item' %>
        <%= link_to 'Sign up', signup_path, class: 'item' %>
      <% end %>
      </div>
    </div>

    <% if logged_in?  %>
    <div class="item">
      <%= link_to current_user.username, "#"%>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |msg_type, msg_content| %>
<div class="ui <%= msg_type %> message transition">
  <i class="close icon"></i>
  <div class="header">
    <% if msg_content.is_a?(Array)%>
      <% msg_content.each do |msg| %>
        <p> <%= msg %> </p>
      <% end %>
    <% else %>
      <%= msg_content %>
    <% end %>
  </div>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div class="ui container">
    <%= render 'layouts/messages'%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
      <div class="event">
        <div class="content">
          <div class="summary">
            <%= message.user.username%>: <%= message.body %>
          </div>
        </div>
      </div>

app/views/messages/index.html.erb
<% @messages.each do |msg| %>

<p> <%= msg.body %> </p>

<% end %>

app/views/users/new.html.erb
<h2 class="ui center aligned big icon header">
  <i class="orange baseball ball icon"></i>
  Signup to have access!
</h2>

<%= form_with(model: @user, local: true, class: 'ui form') do |f| %>
  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username, placeholder: 'Username '%>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: 'example@example.com'%>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <%= f.submit 'Signup', class: 'ui button'%>
<% end %>